server:
  port: 8080

eureka:  
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/api/v1**
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/v1**
